import React from "react"
import { client } from "../../lib/client"
import Head from "next/head"
import { urlFor } from "../../lib/client"
import { nanoid } from "nanoid"
import profPhoto from "../../assets/me3.jpeg"
import avatar from "../../assets/avatar2.png"
import Image from "next/image"
import Link from "next/link"
import { AiFillUpCircle } from "react-icons/ai"
import vector from "../../assets/noBgvector.png"

import useShowOnScroll from "../../hooks/useShowOnScroll"

export default function ProjectDetails({ project }) {
  const { scrollPosition } = useShowOnScroll()
  const {
    name,
    description,
    motivation,
    techStackReasoning,
    FuturePlans,
    liveSite,
    projectImage,
    repo,
    projectGif,
    ssOfHurdle,
    biggestChallenge,
    shortDescription,
    projectImagePlain,
    techStack,
  } = project

  console.log(project)

  const stackRendered = techStack.split(",").map((item) => (
    <p
      className="flex items-center font-bold border-b-2 border-lime-500"
      key={nanoid()}
    >
      {item}
    </p>
  ))

  return (
    <div className="font-sans bg-slate-200 text-sm md:text-lg min-h-screen">
      <Head>
        <title>About {project?.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-left pt-16 py-24 flex flex-col justify-center items-center max-w-4xl mx-auto">
        <div className="w-11/12 flex flex-col gap-20">
          <div className="grid gap-6">
            <h1 className="details-h1">{name.replace(/-/g, " ")}</h1>
            <div className="flex gap-5 font-mono tracking-wide items-center mt-3">
              <div className="overflow-hidden shadow-xl h-14 w-14 rounded-full flex items-center -bottom-32">
                <Image src={profPhoto} alt={"a photo of me"} />
              </div>
              <p>
                made by :{" "}
                <span className="block tracking-widest font-black text-lg">
                  roshane mi<span className="text-lime-600">ll</span>er
                </span>
              </p>
            </div>
          </div>
          <div className="rounded-lg mb-12">
            <img
              height={"600px"}
              width={"100%"}
              className="rounded-lg w-full h-full object-cover object-center -mb-10"
              src={urlFor(projectImage).url()}
              alt={`picture of my ${name} project`}
            />
          </div>

          {motivation && (
            <div>
              <h2 className="details-h2">Motivation</h2>
              <p className="details-p">{motivation}</p>
            </div>
          )}
          <div>
            <h2 className="details-h2">Description</h2>
            <p className="flex items-center">Tech Stack:</p>
            <div className="flex gap-3 mb-4">{stackRendered}</div>
            <p className="details-p">{description}</p>
            <div className="rounded-lg mt-12">
              <img
                height={"600px"}
                width={"100%"}
                className="rounded-lg w-full h-full object-cover object-center"
                src={urlFor(projectGif).url()}
                alt={`gif of my ${name} project`}
              />
            </div>
          </div>
          {biggestChallenge && (
            <div>
              <h2 className="details-h2">Biggest Hurdle</h2>
              <p className="details-p">{biggestChallenge}</p>
              <div className="mt-20 relative">
                <Image
                  className="object-contain h-24 w-24 absolute right-0 top-[-74px]"
                  src={avatar}
                  alt={"pixelated avatar of me"}
                />
                <img
                  className="rounded-lg w-full h-full object-cover object-center"
                  src={urlFor(ssOfHurdle).url()}
                  alt={`screenshot of hurdle faced`}
                />
              </div>
            </div>
          )}
          <div>
            <h2 className="details-h2">FuturePlans</h2>
            <Image
              className="object-cover mx-auto"
              width={"100%"}
              height={"600px"}
              src={vector}
              alt={"a photo of me"}
            />
            <p className="details-p">{FuturePlans}</p>
          </div>
        </div>
      </div>
      <button
        className={`fixed right-5 top-2/3  text-lime-600 ${
          scrollPosition > 1300 ? "block" : "hidden"
        }`}
        onClick={() => {
          if (window && window !== "undefined")
            window.scrollTo({ top: 0, behavior: "smooth" })
        }}
      >
        <AiFillUpCircle className="text-3xl" />
      </button>
    </div>
  )
}

export const getStaticPaths = async () => {
  const query = await client.fetch(`*[_type == "spiceProducts"] {
      slug {
        current
      }
    }`)

  const paths = query.map((item) => {
    return {
      params: {
        slug: item.slug.current,
      },
    }
  })

  return {
    paths,
    fallback: "blocking",
  }
}

export const getStaticProps = async ({ params: { slug } }) => {
  const project = await client.fetch(
    `*[_type == "projects" && slug.current == '${slug}'][0]`
  )

  return {
    props: { project },
  }
}
