import React from "react"
import Nav from "./Nav"
import Footer from "./Footer"
import Header from "./Header"
import Head from "next/head"
import { ProjContext } from "../context/ProjContext"
import { useRouter } from "next/router"

export default function layout({ children }) {
  return (
    <div className="relative text-gray-800 min-h-full bg-rose-300 flex flex-col items-center text-center font-sans md:text-xl">
      <ProjContext>
        <Head>
          <title>Roshanes Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="apple-touch-icon"
            sizes="180x180"
            href="/apple-touch-icon.png"
          />
          <link
            rel="icon"
            type="image/png"
            sizes="32x32"
            href="/favicon-32x32.png"
          />
          <link
            rel="icon"
            type="image/png"
            sizes="16x16"
            href="/favicon-16x16.png"
          />
          <link rel="manifest" href="/site.webmanifest" />
        </Head>
        <Header>
          <Nav />
        </Header>
        <main className="w-full">{children}</main>
        <Footer />
      </ProjContext>
    </div>
  )
}
