import React from "react"
import Nav from "./Nav"
import Footer from "./Footer"
import Header from "./Header"
import Head from "next/head"
import { ProjContext } from "../context/ProjContext"
import { useRouter } from "next/router"

export default function layout({ children }) {
  return (
    <div className="relative text-gray-800 min-h-full bg-rose-300 flex flex-col items-center text-center font-sans md:text-xl">
      <ProjContext>
        <Head>
          <title>Roshanes Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header>
          <Nav />
        </Header>
        <main className="w-full">{children}</main>
        <Footer />
      </ProjContext>
    </div>
  )
}
