import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import Nav from "../components/Nav"
import SkillsButton from "../components/common/SkillsButton"
import profPhoto from "../assets/me3.jpeg"
import { nanoid } from "nanoid"

export default function Home() {
  const mySkills = [
    "HTML",
    "CSS",
    "JS",
    "REACT",
    "NEXT JS",
    "SANITY IO",
    "FIREBASE",
    "GIT",
    "GITHUB",
    "STYLED COMPONENTS",
    "TAILWIND",
    "FIREBASE",
    "STRIPE",
  ]
  return (
    <div className="text-gray-800 min-h-full bg-[url('../assets/bg.jpg')] bg-rose-300 bg-no-repeat bg-cover bg-bottom flex flex-col items-center text-center font-sans">
      <Head>
        <title>Roshanes Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <header className="w-5/6 flex flex-col gap-4 text-left pb-48">
        <h1 className="text-4xl font-bold  mt-16 ">
          Hello world i&apos;m{" "}
          <span className="block">
            &lt;Roshane Mi<span className="text-green-500">ll</span>er/&gt;
          </span>{" "}
          <span>Web Developer</span>
        </h1>
        <p className="font-light text-lg font-mono">
          Former digital artist turned web developer on a constant learning
          path.
        </p>
      </header>
      <main className="bg-gray-900 w-full">
        <article className="pb-8 pt-8 shadow-2xl rounded-lg items-center justify-center bg-slate-100 text-slate-900 w-11/12 mx-auto relative bottom-36 flex flex-wrap gap-5 flex-col-reverse">
          <div className="absolute overflow-hidden shadow-xl h-28 w-28 rounded-full flex items-center -bottom-32">
            <Image src={profPhoto} alt={"a photo of me"} />
          </div>
          <section className="w-5/6 flex flex-col gap-2 items-center">
            <h2 className="font-bold text-2xl">My Skills</h2>
            <div className="flex flex-wrap items-center justify-center gap-3">
              {mySkills.map((skill) => (
                <SkillsButton key={nanoid()}>{skill}</SkillsButton>
              ))}
            </div>
          </section>
          <section className="w-5/6 flex flex-col gap-2 items-center">
            <h2 className="font-bold text-2xl">Background</h2>
            <p className="w-4/5 text-base">
              Completed Scrimba&#39;s Frontend Developer Career Path and several
              other coding challenges online. I have been teaching myself to
              code since 2019 and completed several design and development
              challenges on{" "}
              <a
                target={"_blank"}
                rel="noreferrer"
                href={"https://www.frontendmentor.io/profile/Brezus"}
              >
                frontendmentor.com
              </a>{" "}
              some of those challenges are featured here in this portfolio.
            </p>
          </section>
          <section className="w-5/6 flex flex-col gap-2 items-center">
            <h2 className="font-bold text-2xl">Introduction</h2>
            <p className="w-4/5 text-base">
              Welcome to my web development portfolio! I have been coding since
              high school and have a passion for creating functional and
              visually appealing websites. In my spare time, I enjoy watching
              anime and keeping up with the latest trends in web development.
              Please take a look at some of my recent projects to get an idea of
              my skills and style. I hope you enjoy what you see and feel free
              to contact me with any questions or opportunities. Thank you!
            </p>
          </section>
        </article>
        <article className="bg-slate-100" id={"projects"}>
          <h3>Projects</h3>
        </article>
      </main>

      <footer className="w-5/6"></footer>
    </div>
  )
}
