import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import Nav from "../components/Nav"
import SkillsButton from "../components/common/SkillsButton"

export default function Home() {
  const mySkills = [
    "HTML",
    "CSS",
    "JS",
    "REACT",
    "NEXT JS",
    "SANITY IO",
    "FIREBASE",
    "GIT",
    "GITHUB",
    "STYLED COMPONENTS",
    "TAILWIND",
    "FIREBASE",
    "STRIPE",
  ]
  return (
    <div className="text-rose-50 min-h-full bg-[url('../assets/bg.jpg')] bg-rose-300 bg-no-repeat bg-cover bg-bottom flex flex-col items-center text-center font-sans">
      <Head>
        <title>Roshanes Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <header className="w-5/6 flex flex-col gap-4 text-left pb-48">
        <h1 className="text-4xl font-bold  mt-16 text-rose-50">
          Hello world i&apos;m{" "}
          <span className="block">&lt;Roshane Miller/&gt;</span>{" "}
          <span>Web Developer</span>
        </h1>
        <p className="">
          Former digital artist turned web developer who loves anime and loves
          to code while listening to lofi hip hop on youtube
        </p>
      </header>
      <main className="bg-gray-900 w-full p-10">
        <div className="bg-slate-100 text-slate-900 p-8 w-11/12 mx-auto relative bottom-36 flex flex-col gap-5">
          <p className="font-bold">My Skills</p>
          <div className="flex gap-2 flex-wrap justify-center items-center ">
            {mySkills.map((skill) => (
              <SkillsButton key={crypto.randomUUID}>{skill}</SkillsButton>
            ))}
          </div>
          <p>more about me</p>
          <p>
            Welcome to my web development portfolio! I have been coding since
            high school and have a passion for creating functional and visually
            appealing websites. In my spare time, I enjoy watching anime and
            keeping up with the latest trends in web development. Please take a
            look at some of my recent projects to get an idea of my skills and
            style. I hope you enjoy what you see and feel free to contact me
            with any questions or opportunities. Thank you!
          </p>
        </div>
      </main>

      <footer className="w-5/6"></footer>
    </div>
  )
}
